### PR TITLE
Fix all unit tests

### PR DESCRIPTION
**Pull request by alyssarosenzweig**
none of them were running.

### CODE REVIEW

**Review by CNJasonChen — COMMENTED** [review]
I think when you are auto schedule, you are assigning each employee with task. those task and changing of employee's calendar must be save in the data base.

Also, adding usage of repository is not a violation of CLEAN Architecture. Because you can call repository services to get interaction with Entities.

I think you should use repository to save changes that you made using automatic scheduler

**Comment by alyssarosenzweig** [comment]
> I think when you are auto schedule, you are assigning each employee with task. those task and changing of employee's calendar must be save in the data base.

It is my understanding that calling `Calendar.addEvent` does so, transparent to the scheduler. Therefore the scheduler class does not need to interact with the repository (database layer) directly. The repositories *do* get used, but not by the scheduler class. This simplifies unit testing and reduces coupling.

The repository interface is not a cure all for architectural layering violations. Classes that do not need to interact with the repository/database should not do so.

**Comment by CNJasonChen** [comment]
Calling Calendar.addEvent() will not interact with the data base. Therefore, all changes that we made by the scheduler will not get recorded. Also, we cannot let a entity test to call the repository. That's what I am concerning.

**Comment by alyssarosenzweig** [comment]
>    Calling Calendar.addEvent() will not interact with the data base.

I see, I misunderstood the JPA semantics, frankly they are incompatible
with the project architecture in general. This smells like a layering
violation.

**Comment by CNJasonChen** [comment]
Just to check my understanding with you. when all the employees are created with no Event. Scheduler will automatically Assign shift to them until they reach their max workability. Which will save in our database. Am I right?

**Comment by alyssarosenzweig** [comment]
>    Just to check my understanding with you. when all the employees are
>    created with no Event. Scheduler will automatically Assign shift to them
>    until they reach their max workability. Which will save in our database.
>    Am I right?

That's the idea.

**Comment by CNJasonChen** [comment]
Do you mind revert back the changes in SchedulerImpl Before PR?

**Comment by alyssarosenzweig** [comment]
I've dropped the change in question. This does not require reverting, by the way:

On my branch (note: never do this on the master branch!!!), I typed `git rebase -i origin/master`. It then showed the changes I made as lines prefixed with "pick". I deleted the line that "pick"ed the commit I wanted to drop, and then saved the file and closed the editor. Then the new branch had every commit except for the dropped commit, so I force-pushed it to the branch (DO NOT DO THIS ON MASTER!) with `git push origin tests-2 -f`. This way the git history stays clean -- there is no trace on master of the commit we got rid of :)

**Pull request merged**
