### PR TITLE
Changes:

### PR DESCRIPTION
**Pull request by CNJasonChen**
build.gradle:
+ add JPA framework
+ implement javax persistence to handle entity classes with corresponding repository

Packages:
+ create packages to better organize our project. Package Controller, Repository, Service are created

Employee:
+ add javax.persistence to manage entity classes

Repository:
+ Create example Repository: EmployeeRepository and Event aiming for future developing the database

What next:
- change the entity classes and use JPA to better organize the entities
- creating repository file to connect to the DataBase in the future

### CODE REVIEW

**Comment by CNJasonChen** [comment]
The key changes is creating the packages: Repository, Service, Entity, Controller.

**Comment by alyssarosenzweig** [comment]
Hi, I can't build the code locally

   > Spring Boot plugin requires Gradle 6.8.x, 6.9.x, or 7.x. The current version is Gradle 4.4.1

**Comment by CNJasonChen** [comment]
Can we update it?

**Comment by alyssarosenzweig** [comment]
I've extracted the parts of this PR that I've reviewed into #29 to be merged. I'll leave this open in the mean time. You should git pull once #29 in merged and rebase your changes.

    git fetch origin
    git rebase origin/main

**Comment by alyssarosenzweig** [comment]
I'm not sure what Spring framework is used for here. Could you help me understand that? It looks like javax.persistence has what you need. Thanks.

**Comment by CNJasonChen** [comment]
I am not an expert on the spring framework. The main reason I use this framework is to use CrudRepository interface to help me manage the repository. So, this would help us to create, read, update and delete things from the database.

This is my understanding for now. If i am wrong at some point, please directly message me.

**Pull request closed without merging**
